
# Travis CI configuration for Working PlusPlus++
#
# @see https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# @see https://docs.travis-ci.com/user/database-setup/#postgresql
# @author Tim Malone <tdmalone@gmail.com>

language: node_js
node_js: 10.8.0

services:
  - postgresql

# Support upgrading to PostgreSQL 10, as the default build images don't support it yet.
# (We run the install script in before_install below)
# @see https://github.com/travis-ci/travis-ci/issues/8537#issuecomment-354020356
sudo: required
addons:
  postgresql: 9.6

cache:
  yarn: true
  directories:
    - node_modules

before_install:

  # Upgrade Yarn to the version specified in package.json.
  - curl --location https://yarnpkg.com/install.sh | bash -s -- --version "$( node -e "console.log(require('./package.json').engines.yarn)" )"
  - export PATH="$HOME/.yarn/bin:$PATH"

  # Upgrade to PostgreSQL 10.
  - ./.travis-postgres10.sh

install:
  - yarn --frozen-lockfile

before_script:
  - psql --command="CREATE DATABASE $DATABASE_NAME;" --username="$DATABASE_USER"

script:
  - yarn lint
  - yarn test

# On success, deployments are automatically handled by Heroku.

notifications:
  email: false
  slack:
    on_start: always
    rooms:
      - secure: efl6ZdfE6OTOK5L2z5m993uultsT5WanZ5sn8EmHPa0ENd2+SKXIIigQ1EqbLm1zExWLMKA3Pq5pbHwndsnWywGkZDXWy2eHoSHk7IEVLLvAceyLUr5h2pBL8wztqWGZDMBo1tHGYddQsyBlCs52AQM04i+XBX4tYiUhub7AAbMQ9cqBIz09fRZ9JBNxM6HzMvj+PmeezXzFxvzgvmVQawGQUvJPaZuf9qcwJN1ZWw0FNkIwg3Aafe809mnQnzYIwmiC9kF+ZJ14BX4qqW7uzbo7Zsf647a8LSm9OI3fWzGdNnScWXv+hkWyfHAj8cz4yI2y5l+F3Muhwylp2wHGzjARJTLQq3HTFWaAnZtpyd82FB8v82qKPaPpKTeLcVkdib/E9XjYsdFdsC33jr5vc0j/oM/bLi9pA0faWwN4kq6Q9k3Ei2u+WnP4G7Fzb1WR7zZoLmT9k4BVOJFLYF++OirE9GPaKTvRMnOaR/RO/rQkOx2FlrtzfoG//NBULycMbEMmrv4/GJ64SHQ7YtnedaEb1NwXi/qTwdDtjXkmAeNRoNayHvLLZKG3GKsUze3VIrieN8qMCTRdXRttQd3hacPYNtoCqcB7ogIMN/Jg7v1g2l2szs/v2waNMJW18Hoj3PD8dDSrH/VXlDjaqCNFxo5/sBeHC6eJtW6EkCgzCY4=
