language: node_js
node_js: 10.8.0

cache:
  yarn: true
  directories:
    - node_modules

# Upgrade Yarn to the version specified in package.json.
before_install:
  - curl --location https://yarnpkg.com/install.sh | bash -s -- --version "$( node -e "console.log(require('./package.json').engines.yarn)" )"
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn

script:
  - yarn lint
  - yarn test

# On success, deployments are automatically handled by Heroku.

notifications:
  email: false
  slack:
    on_start: always
    rooms:
      - secure: VVi9+cCUlPf3APgO4VxcTX7tSTNWbSwTaVl6HDJwtaFhdO1JciXjhxT7wMpmduC0Tz5gJSPJBzb9R0LtjWypamEYYh1PhT/239McA72D9ToRPtvpVMcvQNdyP4ekkMmnacOii99XM/kOQZKvu+E6RGG+0DHDJnolQ5iyt4o0Bg9Fwrpb9Mxp3+MlKNVN3JiW7XAc4t69QFgLe4lfyq+/qe0CjFRyAUPYpFLRq1lR1RytXEb+YhCVDLFEcqF5OEh9FuI5F7KHbnoppT0EfeXk5taoPyq9/OXpfVGApUX/s5fAGGvkNWJJGiqCPUWuzByy8aPALwzfJ43tDb0rnGutP5ecJdi2rR63fFGiRIbdg+U8EJbwIW6NxcQdm2qu6CJ132Q2+HuN6nGZt9Kz6q62j3lXUHIaibchkIuilhifZW4TWmWP2iU9hiBin721dV6zsxDUnOR4Y3R9G0YFVCmhp1b63BTkePTriyrlh1hlXqP2VxwQs9Vo+bIo7uFv3Oziq+vMeYWeR9MD0SeCbGOjjKKy3OyBD3InFOcs0ae0ADXVscb3AK1+jQn66QRe+8vPNzOL2gvG2cuJk+JLOw/11z3T/Na9l5ZXVrerN/8xUSRBajg3gdIIX0RSRXIB9LqA0Jy0e364ajp25+zB4sG1TH5pAEG9ZoG3BZOYBc2FXeU=
