version: '3'

services:
  traefik:
    image: traefik:1.6.6-alpine
    container_name: ${PROJECT_NAME}_traefik
    command: --docker
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./.certs:/certs
    networks:
      - proxy
    labels:
      - 'traefik.frontend.rule=Host:monitor.localhost'
      - 'traefik.port=8080'

  nodejs:
    image: node:16
    working_dir: /app
    container_name: ${PROJECT_NAME}_nodejs
    environment:
      NODE_ENV: production
      SCOREBOT_LEADERBOARD_URL: "fe.${PROJECT_NAME}.localhost"
    env_file:
      - .env
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/yarn build
        /usr/local/bin/yarn serve
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - ../:/app
    labels:
      - 'traefik.docker.network=proxy'
      - "traefik.one.frontend.rule=Host:${PROJECT_NAME}.localhost,www.${PROJECT_NAME}.localhost"
      - "traefik.one.port=${SCOREBOT_PORT}"
    ports:
      - '9229:9229'
    networks:
      - proxy
      - default

  frontend:
    image: node:10
    working_dir: /app
    container_name: ${PROJECT_NAME}_frontend
    environment:
      REACT_APP_API_URL: "https://${PROJECT_NAME}.localhost"
    command: 'yarn start'
    tty: true
    restart: unless-stopped
    depends_on:
      - nodejs
    volumes:
      - ../frontend:/app
    labels:
      - "traefik.frontend.rule=Host:fe.${PROJECT_NAME}.localhost,www.fe.${PROJECT_NAME}.localhost"
      - 'traefik.docker.network=proxy'
      - "traefik.port=3000"
    networks:
      - proxy
      - default

  mysql:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_PORT: ${DATABASE_PORT}
    ports:
      - 33061:${DATABASE_PORT}
    volumes:
      - scorebotmysql:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: nazarpc/phpmyadmin
    restart: unless-stopped
    container_name: ${PROJECT_NAME}_phpmyadmin
    labels:
      - "traefik.frontend.rule=Host:pma.${PROJECT_NAME}.localhost"
      - 'traefik.docker.network=proxy'
    environment:
      UPLOAD_SIZE: 64M
    networks:
      - proxy
      - default

  ngrok:
    image: wernight/ngrok
    container_name: ${PROJECT_NAME}_ngrok
    links:
      - nodejs
    labels:
      - "traefik.frontend.rule=Host:ngrok.${PROJECT_NAME}.localhost"
      - 'traefik.docker.network=proxy'
      - 'traefik.port=4040'
    environment:
      - NGROK_LOOK_DOMAIN=nodejs
      - NGROK_PORT=${SCOREBOT_PORT}
      - NGROK_REGION=eu
      - NGROK_AUTH=${NGROK_AUTH}
    networks:
      - proxy
      - default

volumes:
  scorebotmysql:

networks:
  default:
  proxy:
    external: true
